//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z18._01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chlenstvo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chlenstvo()
        {
            this.Pytevkas = new HashSet<Pytevka>();
            this.Students = new HashSet<Student>();
        }
    
        public int NBileta { get; set; }
        public Nullable<System.DateTime> data_vstuplenia { get; set; }
        public System.DateTime data_vihoda { get; set; }
        public Nullable<int> id_oplary { get; set; }
        public Nullable<int> id_student { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pytevka> Pytevkas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
