//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z18._01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oplata
    {
        public int id_oplata { get; set; }
        public Nullable<int> NBileta { get; set; }
        public Nullable<int> Nzaezda { get; set; }
        public Nullable<System.DateTime> god_oplaty { get; set; }
        public string status_oplaty { get; set; }
        public string id_oplaty { get; set; }
        public Nullable<int> id_perioda { get; set; }
    
        public virtual Period Period { get; set; }
    }
}
