//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z18._01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pytevka
    {
        public int id_pytevka { get; set; }
        public Nullable<int> NBileta { get; set; }
        public Nullable<int> Nzaezda { get; set; }
        public Nullable<System.DateTime> god { get; set; }
        public Nullable<System.DateTime> nachalo_zaezda { get; set; }
        public Nullable<System.DateTime> konec_zaezda { get; set; }
        public string status_oplaty { get; set; }
    
        public virtual Chlenstvo Chlenstvo { get; set; }
    }
}
