//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z18._01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int idStudent { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> data_birth { get; set; }
        public string Obrazovanie { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Telephone { get; set; }
        public Nullable<int> NBileta { get; set; }
        public Nullable<int> id_group { get; set; }
        public string other_info { get; set; }
    
        public virtual Chlenstvo Chlenstvo { get; set; }
        public virtual Group Group { get; set; }
    }
}
